id     = "EXPR"
name   = "Expression package"
header = "options/expr_options.h"

[[option]]
  name       = "defaultExprDepth"
  category   = "regular"
  long       = "expr-depth=N"
  type       = "int"
  default    = "0"
  predicates = ["setDefaultExprDepthPredicate"]
  notifies   = ["notifySetDefaultExprDepth"]
  read_only  = true
  help       = "print exprs to depth N (0 == default, -1 == no limit)"

[[option]]
  name       = "defaultDagThresh"
  smt_name   = "dag-thresh"
  category   = "regular"
  long       = "dag-thresh=N"
  type       = "int"
  default    = "1"
  predicates = ["setDefaultDagThreshPredicate"]
  notifies   = ["notifySetDefaultDagThresh"]
  read_only  = true
  help       = "dagify common subexprs appearing > N times (1 == default, 0 == don't dagify)"

[[option]]
  name       = "printExprTypes"
  category   = "regular"
  long       = "print-expr-types"
  type       = "bool"
  default    = "false"
  notifies   = ["notifySetPrintExprTypes"]
  read_only  = true
  help       = "print types with variables when printing exprs"

[[option]]
  name       = "typeChecking"
  category   = "regular"
  long       = "type-checking"
  type       = "bool"
  default    = "DO_SEMANTIC_CHECKS_BY_DEFAULT"
  read_only  = true
  help       = "type check expressions"
