id     = "SETS"
name   = "Sets Theory"

[[option]]
  name       = "setsProxyLemmas"
  category   = "expert"
  long       = "sets-proxy-lemmas"
  type       = "bool"
  default    = "false"
  help       = "introduce proxy variables eagerly to shorten lemmas"

[[option]]
  name       = "setsInferAsLemmas"
  category   = "expert"
  long       = "sets-infer-as-lemmas"
  type       = "bool"
  default    = "true"
  help       = "send inferences as lemmas"

[[option]]
  name       = "setsExt"
  category   = "regular"
  long       = "sets-ext"
  type       = "bool"
  default    = "false"
  help       = "enable extended symbols such as complement and universe in theory of sets"
