name: Python Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: put windows-latest back in (should also test CVC4 on windows-latest in ci.yml)
        # TODO: put macos-latest back in, just removed for debugging linux one
        os: [ubuntu-18.04]
    env:
      # only build for cpython3
      CIBW_BUILD: cp3*
      CIBW_SKIP: cp35*
      CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64
      CIBW_MANYLINUX_I686_IMAGE: quay.io/pypa/manylinux2014_i686
      CIBW_BEFORE_ALL_LINUX: .github/scripts/centos-dependency-installs.sh
      CIBW_BEFORE_ALL_MACOS: .github/scripts/macos-dependency-installs.sh

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      # install from fork to get --no-clean option
      - name: Install cibuildwheel
        run: |
          git clone -b add-no-clean-option https://github.com/makaimann/cibuildwheel.git
          cd cibuildwheel
          python -m pip install -e .
          cd ../

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse --no-clean

      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: ./wheelhouse/*.whl
